# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e67d3769c82971c7e7c5a9345189d01a81e8a1b9b5094ab538663319f9bd1e019fe4e769eb2a1feb3b325e44687fd14226cf1a0a3da3e54e649a110af9734cc

test:
  secret_key_base: 50572475e7e0b346fb9b8d92ae91044ddd4aef9c39639f2a71cff3514fe377a3b56244bf4afa57874d686f9af092b42b089d4bd9a05cfdefdd43b4ed29d4098d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
